### ISSUE TITLE
Does not work with Msal 0.1.3

### ISSUE THREAD

**Issue by dominicusmento** [Gimly/NetCoreAngularAzureB2CMsal#11]
As there is new version of msal.js (0.1.3.) and package.json is configured to acquire it, the whole project does not work anymore until specifically defined to acquire 0.1.2. They changed msal library pretty much so it needs to be solved and updated accordingly.. 

Using 0.1.2 there is problem while trying to "Fetch data" - 401 given while the user has logged in successfully: 
- Could not retrieve token from popup. popup_window_error:Error opening popup window. This can happen if you are using IE or if popups are blocked in the browser.
- GET http://localhost:6420/api/SampleData/WeatherForecasts 401 (Unauthorized)

**Comment by Gimly** [comment]
Thanks, I'm already checking what has changed in the version 0.1.3 of msal.js to see why it isn't working anymore. I'll update as soon as I have figured it out.

The issue using 0.1.2 was caused by a bug that is supposedly fixed in 0.1.3... I was using the version in the lib to make it work. I think the issue we have now is caused by the fact that msal.js is now a module and the `import 'msal'` that I was using actually loads the js and it causes all sorts of issues with the script tag.

**Comment by Gimly** [comment]
OK, new version pushed, tested on my machine and it's working correctly. That new 0.1.3 version is pretty good, they added a module, so I could remove the script tag from the `Index.cshtml`. 

Other than that, nothing major has changed, the issue was probably caused by a version mismatch between what was loaded through NPM and the version in the script tag.

**Comment by dominicusmento** [comment]
Thanks for fast fixing this and implementing support for the msal 0.1.3. 
Unfortunately I still can't get Fetch data to work.
I'm using your config and 6420 port.
From the frontend point of view.. When I try to open fetch data menu, page freezes for 2-3secs, goes for access token I guess and then redirects to Home.. Backend visit isn't visible at all when I look at the 
chrome network with preserve log turned on.
When I try to use acquired access token to make a visit via postman to backend: 
- without authorization header I get 401 which is fine
- with authorization header I don't get any response visiting: 
http://localhost:6420/api/SampleData/WeatherForecasts

Error found in app insights is (action has not been triggered at all): 
![image](https://user-images.githubusercontent.com/7549001/32234550-6d9021fe-be5d-11e7-814a-058bc718e23b.png)

**Comment by spottedmahn** [comment]
>When I try to open fetch data menu, page freezes for 2-3secs

What does the console say?

**Comment by dominicusmento** [comment]
Console
![image](https://user-images.githubusercontent.com/7549001/32235285-53d2328c-be5f-11e7-8326-a4adc896d075.png)
and network
![image](https://user-images.githubusercontent.com/7549001/32235305-61e5bc2c-be5f-11e7-9ab3-5555df5df419.png)
No errors.. both of them are clear..
When the page is 'frozen' network waits for response from the openid-configuration... it resumes after the response is acquired

**Comment by Gimly** [comment]
And what does the backend console say? Looks like you might have an issue with the token validation.

**Comment by dominicusmento** [comment]
The tokens seems to be in invalid state, and yes the server returns an error for validation of the token:
![image](https://user-images.githubusercontent.com/7549001/32316684-87630c18-bfb1-11e7-84a0-1ffca52ac796.png)

Server console:
`msal-netcore-angular> Microsoft.IdentityModel.Tokens.SecurityTokenInvalidAudienceException: IDX10214: Audience validation failed. Audiences: 'e760cab2-b9a1-4c0d-86fb-ff7084abd902'. Did not match: validationParameters.ValidAudience: '25eef6e4-c905-4a07-8eb4-0d08d5df8b3f' or validationParameters.ValidAudiences: 'null'.`

I changed the Audience guid from _25eef6e4..._ to _e760cab2..._ in appsettings.json and now it works from postman - got the results in it, because aud in the token is now correct. 

However it still does not work from frontend.. After the initial login to frontend token seems ok, but after going to fetch data they mess up to whats on the first image..
